### PR TITLE
Use HTTPS Scheme To Perform Archival Operation

### PR DESCRIPTION
**Pull request by brandongalbraith**
Addresses https://github.com/pastpages/savepagenow/issues/9

### CODE REVIEW

**Comment by brandongalbraith** [comment]
Debugging test failures on Python 3.6 and 3.7-dev tests.

**Comment by brandongalbraith** [comment]
Weird, tests pass locally:

```
(savepagenow) ➜  savepagenow git:(master) make test
flake8 savepagenow
coverage run test.py
.
----------------------------------------------------------------------
Ran 1 test in 1.340s

OK
coverage report -m
Name                      Stmts   Miss  Cover   Missing
-------------------------------------------------------
savepagenow/__init__.py       3      0   100%
savepagenow/api.py           51     19    63%   38-42, 46, 51-53, 59-60, 85-86, 122-128, 132
-------------------------------------------------------
TOTAL                        54     19    65%
```

**Comment by brandongalbraith** [comment]
@palewire For your consideration.

**Comment by palewire** [comment]
I reran the tests on Travis and they passed. I suspect the Save Page Now API simply flaked out. It's unreliability is an broader issue for this project but not something to be addressed with this pull request.

**Comment by palewire** [comment]
Thank you for this patch. It has been merged. I hope to release it with a new version of the library soon.

**Comment by brandongalbraith** [comment]
Thank you!

**Comment by palewire** [comment]
The new version has been released on PyPI.

**Pull request merged**
